
LIB_NAME	:= chjson
DEPS		:= chutil chsys

_SRCS		:= json.c \
			   json_helpers.c \
			   parser.c

_TEST_SRCS   := main.c \
			   json.c \
			   json_helpers.c \
			   parser.c

include ../lib_builder_stub.mk
