
LIB_NAME	:= chutil
DEPS		:= chsys
_SRCS		:= list.c \
			   list_helpers.c \
			   map.c \
			   queue.c \
			   heap.c \
			   string.c \
			   stream.c \
			   utf8.c

_TEST_SRCS   := main.c \
			   list.c \
			   list_helpers.c \
			   map.c \
			   queue.c \
			   heap.c \
			   string.c \
			   stream.c \
			   utf8.c


include ../lib_builder_stub.mk
