
LIB_NAME	:= chrpc
DEPS		:= chsys \
			   chutil

_SRCS		:= channel.c \
			   channel_local.c \
			   channel_local2.c

_TEST_SRCS   := main.c \
				channel.c \
				channel_local.c

include ../lib_builder_stub.mk
