
LIB_NAME	:= chrpc
DEPS		:= chsys \
			   chutil

_SRCS		:= channel.c \
			   channel_helpers.c \
			   channel_local.c \
			   channel_local2.c \
			   rpc.c \
			   serial_helpers.c \
			   serial_type.c \
			   serial_value.c

_TEST_SRCS   := main.c \
				channel.c \
				channel_local.c \
				channel_local2.c \
				rpc.c \
				serial_type.c \
				serial_value.c

include ../lib_builder_stub.mk
